package com.jenugumpu.app.localization

fun AppStrings.getString(key: String): String = when (key) {
    StringKeys.APP_NAME -> appName
    StringKeys.TAGLINE -> tagline
    StringKeys.APP_LOGO -> appLogo
    StringKeys.MENU -> menu
    StringKeys.PROFILE -> profile
    StringKeys.BACK -> back
    StringKeys.SELECTED -> selected
    StringKeys.SAVE -> save
    StringKeys.RETRY -> retry
    StringKeys.CANCEL -> cancel
    StringKeys.VERIFY -> verify
    StringKeys.REGISTER -> register
    StringKeys.GO_BACK -> goBack
    StringKeys.ACTIVE -> active
    StringKeys.RECENT -> recent
    StringKeys.ITEMS_COUNT -> itemsCount
    StringKeys.WELCOME_BACK -> welcomeBack
    StringKeys.SIGN_IN_SUBTITLE -> signInSubtitle
    StringKeys.PHONE_NUMBER -> phoneNumber
    StringKeys.SEND_CODE -> sendCode
    StringKeys.CONTINUE_WITH_GOOGLE -> continueWithGoogle
    StringKeys.NO_ACCOUNT_REGISTER -> noAccountRegister
    StringKeys.JOIN_APP -> joinApp
    StringKeys.REGISTER_SUBTITLE -> registerSubtitle
    StringKeys.FULL_NAME -> fullName
    StringKeys.ALREADY_HAVE_ACCOUNT -> alreadyHaveAccount
    StringKeys.VERIFY_OTP -> verifyOtp
    StringKeys.OTP_SUBTITLE -> otpSubtitle
    StringKeys.OTP_CODE -> otpCode
    StringKeys.RESEND_CODE -> resendCode
    StringKeys.WELCOME_BACK_EXCLAIM -> welcomeBackExclaim
    StringKeys.HONEY_FARMER_DASHBOARD -> honeyFarmerDashboard
    StringKeys.TOTAL_HONEY_HARVESTED -> totalHoneyHarvested
    StringKeys.PERCENT_FROM_LAST_MONTH -> percentFromLastMonth
    StringKeys.RECENT_ACTIVITY -> recentActivity
    StringKeys.VIEW_ALL -> viewAll
    StringKeys.HARVESTED_AGO -> harvestedAgo
    StringKeys.NOTIFICATIONS_COMING_SOON -> notificationsComingSoon
    StringKeys.ADD_HARVEST -> addHarvest
    StringKeys.HARVEST_LOG -> harvestLog
    StringKeys.SEARCH_BATCHES -> searchBatches
    StringKeys.READY_FOR_GRADING -> readyForGrading
    StringKeys.PENDING_BATCHES -> pendingBatches
    StringKeys.START_GRADING_NOW -> startGradingNow
    StringKeys.BATCH_HISTORY -> batchHistory
    StringKeys.WILDFLOWER_BATCH -> wildflowerBatch
    StringKeys.BATCH_WEIGHT -> batchWeight
    StringKeys.ADD_NEW_HARVEST -> addNewHarvest
    StringKeys.HARVEST_DETAILS -> harvestDetails
    StringKeys.TOTAL_YIELD_KG -> totalYieldKg
    StringKeys.FLORAL_SOURCE -> floralSource
    StringKeys.CONFIRM_HARVEST -> confirmHarvest
    StringKeys.HONEY_GRADING -> honeyGrading
    StringKeys.GRADING_SYSTEM -> gradingSystem
    StringKeys.FEATURE_COMING_SOON -> featureComingSoon
    StringKeys.SIGN_OUT -> signOut
    StringKeys.LOGOUT_CONFIRM -> logoutConfirm
    StringKeys.CONFIRM_LOGOUT -> confirmLogout
    StringKeys.SETTINGS -> settings
    StringKeys.LOGOUT_DISCLAIMER -> logoutDisclaimer
    StringKeys.EDIT_PROFILE -> editProfile
    StringKeys.PERSONAL_DETAILS -> personalDetails
    StringKeys.EMAIL_ADDRESS -> emailAddress
    StringKeys.FARM_INFORMATION -> farmInformation
    StringKeys.BUSINESS_FARM_NAME -> businessFarmName
    StringKeys.LOCATION -> location
    StringKeys.UPDATE_INFORMATION -> updateInformation
    StringKeys.ACCOUNT -> account
    StringKeys.PREFERENCES -> preferences
    StringKeys.SUPPORT -> support
    StringKeys.PROFILE_INFORMATION -> profileInformation
    StringKeys.PROFILE_INFORMATION_SUBTITLE -> profileInformationSubtitle
    StringKeys.LANGUAGE -> language
    StringKeys.PUSH_NOTIFICATIONS -> pushNotifications
    StringKeys.PUSH_NOTIFICATIONS_SUBTITLE -> pushNotificationsSubtitle
    StringKeys.OFFLINE_MODE -> offlineMode
    StringKeys.OFFLINE_MODE_SUBTITLE -> offlineModeSubtitle
    StringKeys.HELP_CENTER -> helpCenter
    StringKeys.HELP_CENTER_SUBTITLE -> helpCenterSubtitle
    StringKeys.CONTACT_SUPPORT -> contactSupport
    StringKeys.CONTACT_SUPPORT_SUBTITLE -> contactSupportSubtitle
    StringKeys.APPLY_LANGUAGE -> applyLanguage
    StringKeys.REPORTS -> reports
    StringKeys.AVAILABLE_REPORTS -> availableReports
    StringKeys.MONTHLY_PRODUCTION_REPORT -> monthlyProductionReport
    StringKeys.MONTHLY_PRODUCTION_REPORT_SUB -> monthlyProductionReportSub
    StringKeys.PROFIT_SUMMARY_REPORT -> profitSummaryReport
    StringKeys.PROFIT_SUMMARY_REPORT_SUB -> profitSummaryReportSub
    StringKeys.STOCK_INVENTORY_REPORT -> stockInventoryReport
    StringKeys.STOCK_INVENTORY_REPORT_SUB -> stockInventoryReportSub
    StringKeys.GENERATE_PDF_REPORT -> generatePdfReport
    StringKeys.OFFLINE_MODE_TITLE -> offlineModeTitle
    StringKeys.OFFLINE_MODE_DESCRIPTION -> offlineModeDescription
    StringKeys.HARVEST_LOGS_PENDING_SYNC -> harvestLogsPendingSync
    StringKeys.SPECIFIC_RECORDS_WAITING -> specificRecordsWaiting
    StringKeys.PENDING_BATCH -> pendingBatch
    StringKeys.HARVEST_LOG_ENTRY -> harvestLogEntry
    StringKeys.NO_CONNECTION -> noConnection
    StringKeys.CHECK_INTERNET -> checkInternet
    StringKeys.GO_OFFLINE -> goOffline
    StringKeys.ERROR_404_TITLE -> error404Title
    StringKeys.ERROR_404_SUBTITLE -> error404Subtitle
    StringKeys.BACK_TO_HOME -> backToHome
    StringKeys.ERROR_500_TITLE -> error500Title
    StringKeys.ERROR_500_SUBTITLE -> error500Subtitle
    StringKeys.NAV_HOME -> navHome
    StringKeys.NAV_HARVEST -> navHarvest
    StringKeys.NAV_STOCK -> navStock
    StringKeys.NAV_PRICES -> navPrices
    StringKeys.NAV_PROFILE -> navProfile
    StringKeys.ERROR_PHONE_REQUIRED -> errorPhoneRequired
    StringKeys.ERROR_PHONE_INVALID -> errorPhoneInvalid
    StringKeys.ERROR_NAME_REQUIRED -> errorNameRequired
    StringKeys.ERROR_NAME_INVALID -> errorNameInvalid
    StringKeys.ERROR_OTP_INVALID -> errorOtpInvalid
    StringKeys.GOOGLE_SIGN_IN_FAILED -> googleSignInFailed
    StringKeys.GOOGLE_SIGN_IN_CANCELLED -> googleSignInCancelled
    StringKeys.SIGNING_IN -> signingIn
    StringKeys.UPLOAD_NEW_PHOTO -> uploadNewPhoto
    StringKeys.REMOVE_CURRENT_PHOTO -> removeCurrentPhoto
    StringKeys.REMOVE_PROFILE_PICTURE -> removeProfilePicture
    StringKeys.CHANGE_PROFILE_PHOTO -> changeProfilePhoto
    StringKeys.NOTIFICATION_CENTER -> notificationCenter
    StringKeys.CLEAR_ALL -> clearAll
    StringKeys.NO_NOTIFICATIONS -> noNotifications
    StringKeys.CLOSE -> close
    StringKeys.NOTIFICATIONS -> notifications
    StringKeys.HARVEST_SUMMARY_REPORT_TITLE -> harvestSummaryReportTitle
    StringKeys.PDF_GENERATED_ON -> pdfGeneratedOn
    StringKeys.TOTAL_YIELD -> totalYield
    StringKeys.PDF_COLUMN_BATCH -> pdfColumnBatch
    StringKeys.PDF_COLUMN_SOURCE -> pdfColumnSource
    StringKeys.PDF_COLUMN_YIELD -> pdfColumnYield
    StringKeys.PDF_COLUMN_STATUS -> pdfColumnStatus
    StringKeys.PDF_COLUMN_DATE -> pdfColumnDate
    StringKeys.PDF_SAVED_TO_DOWNLOADS -> pdfSavedToDownloads
    StringKeys.PDF_GENERATION_FAILED -> pdfGenerationFailed
    StringKeys.PDF_NO_HARVEST_DATA -> pdfNoHarvestData
    StringKeys.SUPPORT_WHATSAPP_UNAVAILABLE -> supportWhatsappUnavailable
    StringKeys.OPEN_REPORT -> openReport
    StringKeys.SHARE_REPORT -> shareReport
    StringKeys.REPORT_ACTIONS -> reportActions
    else -> key
}
