package com.jenugumpu.app.localization

import androidx.compose.runtime.compositionLocalOf

val LocalAppStrings = compositionLocalOf { LocalizationProvider.strings(AppLanguage.ENGLISH) }

object LocalizationProvider {

    fun strings(language: AppLanguage): AppStrings = when (language) {
        AppLanguage.ENGLISH -> english
        AppLanguage.KANNADA -> kannada
        AppLanguage.HINDI -> hindi
        AppLanguage.TELUGU -> telugu
        AppLanguage.TAMIL -> tamil
        AppLanguage.MALAYALAM -> malayalam
    }

    private val english = AppStrings(
        appName = "Jenu-Gumpu",
        tagline = "BEEKEEPING FOR PROS",
        appLogo = "App Logo",
        menu = "Menu",
        profile = "Profile",
        back = "Back",
        selected = "Selected",
        save = "SAVE",
        retry = "Retry",
        cancel = "Cancel",
        verify = "Verify",
        register = "Register",
        goBack = "Go Back",
        active = "Active",
        recent = "RECENT",
        itemsCount = "5 Items",
        welcomeBack = "Welcome Back",
        signInSubtitle = "Sign in to manage your hives",
        phoneNumber = "Phone Number",
        sendCode = "Send Code",
        continueWithGoogle = "Continue with Google",
        noAccountRegister = "Don't have an account? Register",
        joinApp = "Join Jenu-Gumpu",
        registerSubtitle = "Start tracking your honey production",
        fullName = "Full Name",
        alreadyHaveAccount = "Already have an account? Sign In",
        verifyOtp = "Verify OTP",
        otpSubtitle = "Enter the code sent to your phone",
        otpCode = "OTP Code",
        resendCode = "Resend Code",
        welcomeBackExclaim = "Welcome back!",
        honeyFarmerDashboard = "Honey Farmer Dashboard",
        totalHoneyHarvested = "Total Honey Harvested",
        percentFromLastMonth = "+12% FROM LAST MONTH",
        recentActivity = "Recent Activity",
        viewAll = "View All",
        harvestedAgo = "Harvested 2 hours ago",
        notificationsComingSoon = "Notifications feature coming soon!",
        addHarvest = "Add Harvest",
        harvestLog = "Harvest Log",
        searchBatches = "Search batches...",
        readyForGrading = "Ready for grading",
        pendingBatches = "12 Pending Batches",
        startGradingNow = "START GRADING NOW",
        batchHistory = "Batch History",
        wildflowerBatch = "Wildflower Batch",
        batchWeight = "Wildflower • 15.2 kg",
        addNewHarvest = "Add New Harvest",
        harvestDetails = "Harvest Details",
        totalYieldKg = "Total Yield (kg)",
        floralSource = "Floral Source",
        confirmHarvest = "Confirm Harvest",
        honeyGrading = "Honey Grading",
        gradingSystem = "Grading System",
        featureComingSoon = "This feature is coming soon!",
        signOut = "Sign Out",
        logoutConfirm = "Are you sure you want to logout?",
        confirmLogout = "Confirm Logout",
        settings = "Settings",
        logoutDisclaimer = "Logging out will end your current session. You will need to re-authenticate to access your hive telemetry.",
        editProfile = "Edit Profile",
        personalDetails = "Personal Details",
        emailAddress = "Email Address",
        farmInformation = "Farm Information",
        businessFarmName = "Business/Farm Name",
        location = "Location",
        updateInformation = "Update Information",
        account = "Account",
        preferences = "Preferences",
        support = "Support",
        profileInformation = "Profile Information",
        profileInformationSubtitle = "Update your name and hive details",
        language = "Language",
        pushNotifications = "Push Notifications",
        pushNotificationsSubtitle = "Receive alerts for harvest cycles",
        offlineMode = "Offline Mode",
        offlineModeSubtitle = "Keep using app without internet",
        helpCenter = "Help Center",
        helpCenterSubtitle = "Documentation and guides",
        contactSupport = "Contact Support",
        contactSupportSubtitle = "Get in touch with our team",
        applyLanguage = "Apply Language",
        reports = "Reports",
        availableReports = "Available Reports",
        monthlyProductionReport = "Monthly Production Report",
        monthlyProductionReportSub = "Summary of harvest volumes",
        profitSummaryReport = "Profit Summary Report",
        profitSummaryReportSub = "Comprehensive financial overview",
        stockInventoryReport = "Stock Inventory Report (PDF)",
        stockInventoryReportSub = "Detailed breakdown of honey stock",
        generatePdfReport = "Generate PDF Report",
        offlineModeTitle = "You're in offline mode",
        offlineModeDescription = "Changes will sync automatically when your connection is restored.",
        harvestLogsPendingSync = "5 HARVEST LOGS PENDING SYNC",
        specificRecordsWaiting = "SPECIFIC RECORDS WAITING",
        pendingBatch = "Pending Batch",
        harvestLogEntry = "Harvest Log • 14.5 kg",
        noConnection = "No Connection",
        checkInternet = "Please check your internet connection",
        goOffline = "Go Offline",
        error404Title = "Oops! Page missing",
        error404Subtitle = "The hive you're looking for doesn't exist",
        backToHome = "Back to Home",
        error500Title = "Something went wrong",
        error500Subtitle = "Our bees are working on a fix",
        navHome = "Home",
        navHarvest = "Harvest",
        navStock = "Stock",
        navPrices = "Prices",
        navProfile = "Profile",
        errorPhoneRequired = "Phone number is required",
        errorPhoneInvalid = "Enter a valid 10-digit phone number",
        errorNameRequired = "Full name is required",
        errorNameInvalid = "Name must be at least 2 letters",
        errorOtpInvalid = "Enter the 6-digit code",
        googleSignInFailed = "Google sign-in failed. Try again.",
        googleSignInCancelled = "Google sign-in was cancelled",
        signingIn = "Signing in…",
        uploadNewPhoto = "Upload New Photo",
        removeCurrentPhoto = "Remove Current Photo",
        changeProfilePhoto = "Change Profile Photo",
        notificationCenter = "Notification Center",
        clearAll = "Clear All",
        noNotifications = "No recent activity",
        close = "Close",
        notifications = "Notifications",
        harvestSummaryReportTitle = "Harvest Summary",
        pdfGeneratedOn = "Generated on",
        totalYield = "Total yield",
        pdfColumnBatch = "Batch",
        pdfColumnSource = "Floral source",
        pdfColumnYield = "Yield (kg)",
        pdfColumnStatus = "Status",
        pdfColumnDate = "Harvested",
        pdfSavedToDownloads = "Report saved to Downloads",
        pdfGenerationFailed = "Could not generate report",
        openReport = "Open",
        shareReport = "Share",
        reportActions = "Report ready",
    )

    private val kannada = AppStrings(
        appName = "ಜೇನು-ಗುಂಪು",
        tagline = "ವೃತ್ತಿಪರ ಮधುಸಾಕಣೆ",
        appLogo = "ಅಪ್ಲಿಕೇಶನ್ ಲೋಗೋ",
        menu = "ಮೆನು",
        profile = "ಪ್ರೊಫೈಲ್",
        back = "ಹಿಂದೆ",
        selected = "ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ",
        save = "ಉಳಿಸಿ",
        retry = "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
        cancel = "ರದ್ದುಮಾಡಿ",
        verify = "ಪರಿಶೀಲಿಸಿ",
        register = "ನೋಂದಣಿ",
        goBack = "ಹಿಂದೆ ಹೋಗಿ",
        active = "ಸಕ್ರಿಯ",
        recent = "ಇತ್ತೀಚಿನ",
        itemsCount = "5 ವಸ್ತುಗಳು",
        welcomeBack = "ಮತ್ತೆ ಸ್ವಾಗತ",
        signInSubtitle = "ನಿಮ್ಮ ಜೇನುಗೂಡುಗಳನ್ನು ನಿರ್ವಹಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
        phoneNumber = "ಫೋನ್ ಸಂಖ್ಯೆ",
        sendCode = "ಕೋಡ್ ಕಳುಹಿಸಿ",
        continueWithGoogle = "Google ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ",
        noAccountRegister = "ಖಾತೆ ಇಲ್ಲವೇ? ನೋಂದಣಿ ಮಾಡಿ",
        joinApp = "ಜೇನು-ಗುಂಪುಗೆ ಸೇರಿ",
        registerSubtitle = "ನಿಮ್ಮ ಜೇನು ಉತ್ಪಾದನೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ",
        fullName = "ಪೂರ್ಣ ಹೆಸರು",
        alreadyHaveAccount = "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಸೈನ್ ಇನ್",
        verifyOtp = "OTP ಪರಿಶೀಲಿಸಿ",
        otpSubtitle = "ನಿಮ್ಮ ಫೋನ್‌ಗೆ ಕಳುಹಿಸಿದ ಕೋಡ್ ನಮೂದಿಸಿ",
        otpCode = "OTP ಕೋಡ್",
        resendCode = "ಕೋಡ್ ಮತ್ತೆ ಕಳುಹಿಸಿ",
        welcomeBackExclaim = "ಮತ್ತೆ ಸ್ವಾಗತ!",
        honeyFarmerDashboard = "ಜೇನು ರೈತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        totalHoneyHarvested = "ಒಟ್ಟು ಜೇನು ಸಂಗ್ರಹ",
        percentFromLastMonth = "ಕಳೆದ ತಿಂಗಳಿಗಿಂತ +12%",
        recentActivity = "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
        viewAll = "ಎಲ್ಲಾ ವೀಕ್ಷಿಸಿ",
        harvestedAgo = "2 ಗಂಟೆಗಳ ಹಿಂದೆ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ",
        notificationsComingSoon = "ಅಧಿಸೂಚನೆ ವೈಶಿಷ್ಟ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!",
        addHarvest = "ಸಂಗ್ರಹ ಸೇರಿಸಿ",
        harvestLog = "ಸಂಗ್ರಹ ಲಾಗ್",
        searchBatches = "ಬ್ಯಾಚ್‌ಗಳನ್ನು ಹುಡುಕಿ...",
        readyForGrading = "ಗ್ರೇಡಿಂಗ್‌ಗೆ ಸಿದ್ಧ",
        pendingBatches = "12 ಬಾಕಿ ಬ್ಯಾಚ್‌ಗಳು",
        startGradingNow = "ಈಗ ಗ್ರೇಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
        batchHistory = "ಬ್ಯಾಚ್ ಇತಿಹಾಸ",
        wildflowerBatch = "ವೈಲ್ಡ್‌ಫ್ಲವರ್ ಬ್ಯಾಚ್",
        batchWeight = "ವೈಲ್ಡ್‌ಫ್ಲವರ್ • 15.2 kg",
        addNewHarvest = "ಹೊಸ ಸಂಗ್ರಹ ಸೇರಿಸಿ",
        harvestDetails = "ಸಂಗ್ರಹ ವಿವರಗಳು",
        totalYieldKg = "ಒಟ್ಟು ಇಳುವರಿ (kg)",
        floralSource = "ಹೂವಿನ ಮೂಲ",
        confirmHarvest = "ಸಂಗ್ರಹ ದೃಢೀಕರಿಸಿ",
        honeyGrading = "ಜೇನು ಗ್ರೇಡಿಂಗ್",
        gradingSystem = "ಗ್ರೇಡಿಂಗ್ ವ್ಯವಸ್ಥೆ",
        featureComingSoon = "ಈ ವೈಶಿಷ್ಟ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!",
        signOut = "ಸೈನ್ ಔಟ್",
        logoutConfirm = "ನೀವು ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಖಚಿತವೇ?",
        confirmLogout = "ಲಾಗ್ ಔಟ್ ದೃಢೀಕರಿಸಿ",
        settings = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        logoutDisclaimer = "ಲಾಗ್ ಔಟ್ ಮಾಡುವುದರಿಂದ ನಿಮ್ಮ ಸೆಷನ್ ಮುಗಿಯುತ್ತದೆ. ಜೇನುಗೂಡು ಟೆಲಿಮೆಟ್ರಿ ಪ್ರವೇಶಿಸಲು ಮತ್ತೆ ದೃಢೀಕರಣ ಅಗತ್ಯ.",
        editProfile = "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
        personalDetails = "ವೈಯಕ್ತಿಕ ವಿವರಗಳು",
        emailAddress = "ಇಮೇಲ್ ವಿಳಾಸ",
        farmInformation = "ಫಾರ್ಮ್ ಮಾಹಿತಿ",
        businessFarmName = "ವ್ಯಾಪಾರ/ಫಾರ್ಮ್ ಹೆಸರು",
        location = "ಸ್ಥಳ",
        updateInformation = "ಮಾಹಿತಿ ನವೀಕರಿಸಿ",
        account = "ಖಾತೆ",
        preferences = "ಆದ್ಯತೆಗಳು",
        support = "ಬೆಂಬಲ",
        profileInformation = "ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿ",
        profileInformationSubtitle = "ನಿಮ್ಮ ಹೆಸರು ಮತ್ತು ಜೇನುಗೂಡು ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ",
        language = "ಭಾಷೆ",
        pushNotifications = "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",
        pushNotificationsSubtitle = "ಸಂಗ್ರಹ ಚಕ್ರಗಳಿಗೆ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ",
        offlineMode = "ಆಫ್‌ಲೈನ್ ಮೋಡ್",
        offlineModeSubtitle = "ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆ ಅಪ್ಲಿಕೇಶನ್ ಬಳಸಿ",
        helpCenter = "ಸಹಾಯ ಕೇಂದ್ರ",
        helpCenterSubtitle = "ದಾಖಲೆಗಳು ಮತ್ತು ಮಾರ್ಗದರ್ಶಿಗಳು",
        contactSupport = "ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ",
        contactSupportSubtitle = "ನಮ್ಮ ತಂಡವನ್ನು ಸಂಪರ್ಕಿಸಿ",
        applyLanguage = "ಭಾಷೆ ಅನ್ವಯಿಸಿ",
        reports = "ವರದಿಗಳು",
        availableReports = "ಲಭ್ಯವಿರುವ ವರದಿಗಳು",
        monthlyProductionReport = "ಮಾಸಿಕ ಉತ್ಪಾದನಾ ವರದಿ",
        monthlyProductionReportSub = "ಸಂಗ್ರಹ ಪ್ರಮಾಣದ ಸಾರಾಂಶ",
        profitSummaryReport = "ಲಾಭ ಸಾರಾಂಶ ವರದಿ",
        profitSummaryReportSub = "ಸಮಗ್ರ ಆರ್ಥಿಕ ಅವಲೋಕನ",
        stockInventoryReport = "ಸ್ಟಾಕ್ ಇನ್ವೆಂಟರಿ ವರದಿ (PDF)",
        stockInventoryReportSub = "ಜೇನು ಸ್ಟಾಕ್ ವಿವರವಾದ ವಿಭಜನೆ",
        generatePdfReport = "PDF ವರದಿ ರಚಿಸಿ",
        offlineModeTitle = "ನೀವು ಆಫ್‌ಲೈನ್ ಮೋಡ್‌ನಲ್ಲಿದ್ದೀರಿ",
        offlineModeDescription = "ಸಂಪರ್ಕ ಮರುಸ್ಥಾಪಿಸಿದಾಗ ಬದಲಾವಣೆಗಳು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಿಂಕ್ ಆಗುತ್ತವೆ.",
        harvestLogsPendingSync = "5 ಸಂಗ್ರಹ ಲಾಗ್‌ಗಳು ಸಿಂಕ್ ಬಾಕಿ",
        specificRecordsWaiting = "ನಿರ್ದಿಷ್ಟ ದಾಖಲೆಗಳು ಕಾಯುತ್ತಿವೆ",
        pendingBatch = "ಬಾಕಿ ಬ್ಯಾಚ್",
        harvestLogEntry = "ಸಂಗ್ರಹ ಲಾಗ್ • 14.5 kg",
        noConnection = "ಸಂಪರ್ಕವಿಲ್ಲ",
        checkInternet = "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ",
        goOffline = "ಆಫ್‌ಲೈನ್ ಹೋಗಿ",
        error404Title = "ಓಹ್! ಪುಟ ಕಾಣೆಯಾಗಿದೆ",
        error404Subtitle = "ನೀವು ಹುಡುಕುತ್ತಿರುವ ಜೇನುಗೂಡು ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ",
        backToHome = "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
        error500Title = "ಏನೋ ತಪ್ಪಾಗಿದೆ",
        error500Subtitle = "ನಮ್ಮ ಜೇನುನೊಣಗಳು ಸರಿಪಡಿಸಲು ಕೆಲಸ ಮಾಡುತ್ತಿವೆ",
        navHome = "ಮುಖಪುಟ",
        navHarvest = "ಸಂಗ್ರಹ",
        navStock = "ಸ್ಟಾಕ್",
        navPrices = "ಬೆಲೆಗಳು",
        navProfile = "ಪ್ರೊಫೈಲ್",
        errorPhoneRequired = "ಫೋನ್ ಸಂಖ್ಯೆ ಅಗತ್ಯವಿದೆ",
        errorPhoneInvalid = "ಮಾನ್ಯ 10-ಅಂಕಿಯ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
        errorNameRequired = "ಪೂರ್ಣ ಹೆಸರು ಅಗತ್ಯವಿದೆ",
        errorNameInvalid = "ಹೆಸರು ಕನಿಷ್ಠ 2 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು",
        errorOtpInvalid = "6-ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ",
        googleSignInFailed = "Google ಸೈನ್-ಇನ್ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
        googleSignInCancelled = "Google ಸೈನ್-ಇನ್ ರದ್ದಾಗಿದೆ",
        signingIn = "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ…",
        uploadNewPhoto = "ಹೊಸ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        removeCurrentPhoto = "ಪ್ರಸ್ತುತ ಫೋಟೋ ತೆಗೆದುಹಾಕಿ",
        changeProfilePhoto = "ಪ್ರೊಫೈಲ್ ಫೋಟೋ ಬದಲಾಯಿಸಿ",
        notificationCenter = "ಅಧಿಸೂಚನಾ ಕೇಂದ್ರ",
        clearAll = "ಎಲ್ಲಾ ತೆರವುಗೊಳಿಸಿ",
        noNotifications = "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ ಇಲ್ಲ",
        close = "ಮುಚ್ಚಿ",
        notifications = "ಅಧಿಸೂಚನೆಗಳು",
        harvestSummaryReportTitle = "ಸಂಗ್ರಹ ಸಾರಾಂಶ",
        pdfGeneratedOn = "ರಚಿಸಿದ ದಿನಾಂಕ",
        totalYield = "ಒಟ್ಟು ಇಳುವರಿ",
        pdfColumnBatch = "ಬ್ಯಾಚ್",
        pdfColumnSource = "ಹೂವಿನ ಮೂಲ",
        pdfColumnYield = "ಇಳುವರಿ (kg)",
        pdfColumnStatus = "ಸ್ಥಿತಿ",
        pdfColumnDate = "ಸಂಗ್ರಹಿಸಿದ ದಿನಾಂಕ",
        pdfSavedToDownloads = "ವರದಿ ಡೌನ್‌ಲೋಡ್‌ಗಳಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ",
        pdfGenerationFailed = "ವರದಿ ರಚಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",
        openReport = "ತೆರೆಯಿರಿ",
        shareReport = "ಹಂಚಿಕೊಳ್ಳಿ",
        reportActions = "ವರದಿ ಸಿದ್ಧವಾಗಿದೆ",
    )

    private val hindi = english.copy(
        appName = "जेनु-गंपु",
        tagline = "पेशेवरों के लिए मधुमक्खी पालन",
        menu = "मेनू", profile = "प्रोफ़ाइल", back = "वापस",
        welcomeBack = "वापसी पर स्वागत है",
        signInSubtitle = "अपने छत्तों को प्रबंधित करने के लिए साइन इन करें",
        phoneNumber = "फ़ोन नंबर", sendCode = "कोड भेजें",
        settings = "सेटिंग्स", language = "भाषा",
        applyLanguage = "भाषा लागू करें",
        harvestLog = "फसल लॉग", reports = "रिपोर्ट",
        signOut = "साइन आउट", editProfile = "प्रोफ़ाइल संपादित करें",
        navHome = "होम", navHarvest = "फसल", navStock = "स्टॉक",
        navPrices = "कीमतें", navProfile = "प्रोफ़ाइल",
    )

    private val telugu = english.copy(
        appName = "జేను-గుంపు",
        tagline = "ప్రొఫెషనల్స్ కోసం తేనె పెంపకం",
        menu = "మెనూ", profile = "ప్రొఫైల్", back = "వెనుకకు",
        welcomeBack = "మళ్ళీ స్వాగతం",
        signInSubtitle = "మీ తేనెటీగలను నిర్వహించడానికి సైన్ ఇన్ చేయండి",
        phoneNumber = "ఫోన్ నంబర్", sendCode = "కోడ్ పంపండి",
        settings = "సెట్టింగ్‌లు", language = "భాష",
        applyLanguage = "భాష వర్తింపజేయండి",
        harvestLog = "పంట లాగ్", reports = "నివేదికలు",
        signOut = "సైన్ అవుట్", editProfile = "ప్రొఫైల్ సవరించండి",
        navHome = "హోమ్", navHarvest = "పంట", navStock = "స్టాక్",
        navPrices = "ధరలు", navProfile = "ప్రొఫైల్",
    )

    private val tamil = english.copy(
        appName = "ஜேனு-கும்பு",
        tagline = "தொழில்முறை தேனீ வளர்ப்பு",
        menu = "மெனு", profile = "சுயவிவரம்", back = "பின்செல்",
        welcomeBack = "மீண்டும் வரவேற்கிறோம்",
        signInSubtitle = "உங்கள் கூடுகளை நிர்வகிக்க உள்நுழையுங்கள்",
        phoneNumber = "தொலைபேசி எண்", sendCode = "குறியீடு அனுப்பு",
        settings = "அமைப்புகள்", language = "மொழி",
        applyLanguage = "மொழியைப் பயன்படுத்து",
        harvestLog = "அறுவடை பதிவு", reports = "அறிக்கைகள்",
        signOut = "வெளியேறு", editProfile = "சுயவிவரத்தைத் திருத்து",
        navHome = "முகப்பு", navHarvest = "அறுவடை", navStock = "பங்கு",
        navPrices = "விலைகள்", navProfile = "சுயவிவரம்",
    )

    private val malayalam = english.copy(
        appName = "ജേനു-ഗുംപു",
        tagline = "പ്രൊഫഷണലുകൾക്കുള്ള തേനീപരിപാലനം",
        menu = "മെനു", profile = "പ്രൊഫൈൽ", back = "പിന്നോട്ട്",
        welcomeBack = "വീണ്ടും സ്വാഗതം",
        signInSubtitle = "നിങ്ങളുടെ തേനീകൂടുകൾ നിയന്ത്രിക്കാൻ സൈൻ ഇൻ ചെയ്യുക",
        phoneNumber = "ഫോൺ നമ്പർ", sendCode = "കോഡ് അയയ്ക്കുക",
        settings = "ക്രമീകരണങ്ങൾ", language = "ഭാഷ",
        applyLanguage = "ഭാഷ പ്രയോഗിക്കുക",
        harvestLog = "വിളവെടുപ്പ് ലോഗ്", reports = "റിപ്പോർട്ടുകൾ",
        signOut = "സൈൻ ഔട്ട്", editProfile = "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക",
        navHome = "ഹോം", navHarvest = "വിളവെടുപ്പ്", navStock = "സ്റ്റോക്ക്",
        navPrices = "വിലകൾ", navProfile = "പ്രൊഫൈൽ",
    )
}

@androidx.compose.runtime.Composable
fun appStrings(): AppStrings = LocalAppStrings.current
